HOSTNAME = "https://bookmarks.bskv.site"
SERVICE_DID_WEB = "did:web:bookmarks.bskv.site"
SERVICE_DID_PLC = "did:plc:qvmvynssslo5yhstrnc2cwv6"
BOOKMARKS_URI = "at://did:plc:qvmvynssslo5yhstrnc2cwv6/app.bsky.feed.generator/bookmarks"
GIT_REPO_URL = "https://biskuvi-app.github.io"
BOOKMARKS_DIR = "repo_bookmarks"
LOGS_DIR = "logs"
