[project]
name = "bookmark-server"
version = "0.1.0"
description = "Server to keep bookmarks (post AT URIs)"
readme = "README.md"
requires-python = "~=3.10"
dependencies = [
    "atproto>=0.0.55",
    "flask-cors>=5.0.0",
    "flask>=3.0.3",
    "python-dotenv>=1.0.1",
]
